services:
  fastapi:
    build: .
    container_name: cicd-fastapi
    ports:
      - '80:80'
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: cicd-postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: